//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diseno
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Transaccions = new HashSet<Transaccion>();
        }
    
        public int idProducto { get; set; }
        public string Nombre { get; set; }
        public decimal precio { get; set; }
        public int coleccion { get; set; }
        public int stock { get; set; }
        public int idTienda { get; set; }

        [JsonIgnore]
        public virtual Coleccion Coleccion1 { get; set; }
        [JsonIgnore]
        public virtual Tienda Tienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Transaccion> Transaccions { get; set; }
    }
}
